# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('orderNumber', models.CharField(max_length=255, unique=True, verbose_name='订单号')),
                ('userImage', models.ImageField(upload_to='images', verbose_name='用户个人信息界面截图')),
                ('orderImage', models.ImageField(upload_to='images', verbose_name='订单界面截图')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否通过审核')),
                ('uploader', models.CharField(max_length=32, verbose_name='邀请人 (选填)')),
                ('pubdate', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
                ('payAccount', models.CharField(blank=True, max_length=255, null=True, verbose_name='支付宝账号 (我方发放奖励金渠道)')),
                ('phoneNumber', models.BigIntegerField(blank=True, null=True, verbose_name='手机号 (无支付宝账户可选填)')),
                ('filepath', models.CharField(blank=True, max_length=255, null=True, verbose_name='上传Excel的文件路径')),
            ],
            options={
                'verbose_name': '用户上传资料',
                'verbose_name_plural': '用户上传资料',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='姓名')),
            ],
        ),
    ]
