# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yitaoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadinfo',
            name='pubdatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='uploadinfo',
            name='pubdate',
            field=models.DateField(auto_now=True, verbose_name='上传日期'),
        ),
    ]
