# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('yitaoApp', '0002_auto_20190412_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadinfo',
            options={'ordering': ('-pubdate',), 'verbose_name': '用户上传资料', 'verbose_name_plural': '用户上传资料'},
        ),
        migrations.AddField(
            model_name='uploadinfo',
            name='imgpath',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='上传图片文件夹路径,以当日日期命名'),
        ),
        migrations.AlterField(
            model_name='uploadinfo',
            name='orderImage',
            field=models.ImageField(storage=system.storage.ImageStorage(), upload_to='images', verbose_name='订单界面截图'),
        ),
        migrations.AlterField(
            model_name='uploadinfo',
            name='userImage',
            field=models.ImageField(storage=system.storage.ImageStorage(), upload_to='images', verbose_name='用户个人信息界面截图'),
        ),
    ]
