# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yitaoApp', '0002_auto_20190412_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadinfo',
            name='phoneNumber',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='手机号 (无支付宝账户可选填)'),
        ),
    ]
